# Generated by Django 4.0.2 on 2022-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Актер')),
                ('photo', models.ImageField(upload_to='actors/', verbose_name='Фото актера')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Режиссер')),
                ('photo', models.ImageField(upload_to='producers/', verbose_name='Фото режиссера')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название фильма')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('year', models.IntegerField(verbose_name='Год выхода фильма')),
                ('raiting_IMDB', models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDB')),
                ('raititng_KP', models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиска')),
                ('poster', models.ImageField(upload_to='poster/', verbose_name='Постер фильма')),
                ('budget', models.PositiveIntegerField(verbose_name='Бюджет')),
                ('actors', models.ManyToManyField(related_name='film_actors', to='main_page.Actor', verbose_name='актеры')),
                ('genre', models.ManyToManyField(related_name='film_genres', to='main_page.Genre', verbose_name='жанры')),
                ('producers', models.ManyToManyField(related_name='film_producers', to='main_page.Producer', verbose_name='режиссеры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
